#ifndef ISR_H
#define ISR_H

void reset_handler (void);
void Default_handler(void);
void NMI_handler(void);
void HardFault_handler(void);
void MemManage_handler(void);
void BusFault_handler(void);
void UsuageFault_handler(void);
void SVCall_handler (void);
void DebugMonitor_handler(void);
void PendSV_handler (void);
void Systick_handler(void);
void WWDG_handler(void);
void EXTI16_PVD__handler(void);
void EXTI21_TAMP_STAMP_handler(void);
void EXTI22_RTC_WKUP_handler(void);
void FLASH_handler                (void);
void RCC_handler                  (void);
void EXTI0_handler                (void);
void EXTI1_handler                (void);
void EXTI2_handler                (void);
void EXTI3_handler                (void);
void EXTI4_handler                (void);
void DMA1_Stream0_handler         (void);
void DMA1_Stream1_handler         (void);
void DMA1_Stream2_handler         (void);
void DMA1_Stream3_handler         (void);
void DMA1_Stream4_handler         (void);
void DMA1_Stream5_handler         (void);
void DMA1_Stream6_handler         (void);
void ADC_handler                  (void);
void EXTI9_5__handler             (void);
void TIM1_BRK_TIM9_handler        (void);
void TIM1_UP_TIM10_handler        (void);
void TIM1_TRG_COM_TIM11_handler   (void);
void TIM1_CC_handler              (void);
void TIM2_handler                 (void);
void TIM3_handler                 (void);
void TIM4_handler                 (void);
void I2C1_EV_handler              (void);
void I2C1_ER_handler              (void);
void I2C2_EV_handler              (void);
void I2C2_ER_handler              (void);
void SPI1_handler                 (void);
void SPI2_handler                 (void);
void USART1_handler               (void);
void USART2_handler               (void);
void EXTI15_10_handler            (void);
void EXTI17_RTC_Alarm_handler     (void);
void EXTI18_OTG_FS_WKUP_handler   (void);
void DMA1_Stream7_handler         (void);
void SDIO_handler                 (void);
void TIM5_handler                 (void);
void SPI3_handler                 (void);
void DMA2_Stream0_handler                 (void);
void DMA2_Stream1_handler                 (void);
void DMA2_Stream2_handler                 (void);
void DMA2_Stream3_handler                 (void);
void DMA2_Stream4_handler                 (void);
void OTG_FS_handler                       (void);
void DMA2_Stream5_handler                 (void);
void DMA2_Stream6_handler                 (void);
void DMA2_Stream7_handler                 (void);
void USART6_handler                        (void);
void I2C3_EV_handler                      (void);
void I2C3_ER_handler                      (void);
void FPU_handler                          (void);
void SPI4_handler                         (void);

#endif
